train:
  _target_: dataloaders.extended_action_dataset.ExtendedActionDataset
  config:
    _target_: dataloaders.utils.DataLoaderConfig
    dataset_root: ${env_vars.data_root.train}
    trajectory_roots:
      _target_: dataloaders.utils.load_trajectory_roots
      trajectory_root_path: ${dataset.train.config.dataset_root}/r3d_files.txt
      original_root: ${env_vars.data_original_root.train}
      new_root: ${dataset.train.config.dataset_root}
    include_tasks: 
      - ${include_task}
    exclude_homes: []
    exclude_envs: []
    sequence_length: 1
    control_timeskip: ${control_timeskip}
    safe_action_threshold: 0.05
    relative_gripper: False
    use_depth: ${use_depth}
  only_action_return: True
  max_videoreaders_in_memory: 64
  shuffle_mode: RANDOM_ORDER
  device: cpu
  num_extra_actions: 0


test:
  _target_: dataloaders.extended_action_dataset.ExtendedActionDataset
  config:
    _target_: dataloaders.utils.DataLoaderConfig
    dataset_root: ${env_vars.data_root.val}
    trajectory_roots:
      _target_: dataloaders.utils.load_trajectory_roots
      trajectory_root_path: ${dataset.test.config.dataset_root}/r3d_files.txt
      original_root: ${env_vars.data_original_root.val}
      new_root: ${dataset.test.config.dataset_root}
    include_tasks: 
      - ${include_task}
    exclude_homes: []
    exclude_envs: []
    sequence_length: 1
    control_timeskip: ${control_timeskip}
    safe_action_threshold: 0.05
    relative_gripper: False
    use_depth: ${use_depth}
  only_action_return: True
  max_videoreaders_in_memory: 64
  shuffle_mode: RANDOM_ORDER
  device: cpu
  num_extra_actions: 0
